### ISSUE TITLE
AssertionError: Padding value causes wrapping around more than once.

### ISSUE THREAD

**Issue by dvschultz** [JCBrouwer/maua-stylegan2#16]
Tried with a variety of models (converted from sg2 and ada) and keep getting this error

```generating noise...
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-34-99ce6593ca14> in <module>()
     14   initialize=initialize,
     15   get_latents=get_latents,
---> 16   get_noise=get_noise,
     17   # get_bends=get_bends, # if you're running a 1024px network you can uncomment this for 1920x1080 output
     18 )

4 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in _pad_circular(input, padding)
   4400     for idx, size in enumerate(paddable_shape):
   4401         # Only supports wrapping around once
-> 4402         assert padding[-(idx * 2 + 1)] <= size, "Padding value causes wrapping around more than once."
   4403         assert padding[-(idx * 2 + 2)] <= size, "Padding value causes wrapping around more than once."
   4404         # Negative padding should not result in negative sizes

AssertionError: Padding value causes wrapping around more than once.```

**Comment by dvschultz** [comment]
This look to be a Colab dependency issue. Running it locally with your env.yml file works fine. Will leave open if you want to debug, feel free to close otherwise.

**Comment by JCBrouwer** [comment]
How long is the audio you're trying to generate?

I believe this is related to the gaussian filter's convolution kernel being larger than the number of frames in the audio.

[I tried fixing this at some point](https://github.com/JCBrouwer/maua-stylegan2/blob/master/audioreactive/signal.py#L329) but I seem to remember that it was messing up results when it shouldn't.

You should be able to fix it just by lowering any high values in gaussian filters like `gaussian_filter(..., 128)`. I think a value of 32 should be plenty smooth for most cases.

**Comment by JCBrouwer** [comment]
Looking through again I think I see where my last fix went wrong. If you

**Comment by JCBrouwer** [comment]
woops

**Comment by JCBrouwer** [comment]
Looking over it again I think I see where my last fix went wrong, let me see if I can make a test case.

**Comment by JCBrouwer** [comment]
Alright I've pushed a fix to [this branch](https://github.com/JCBrouwer/maua-stylegan2/tree/fix%2316) would you mind trying it out and seeing if the results are OK?
