### ISSUE TITLE
Compatibility with StyleGAN3

### ISSUE THREAD

**Issue by mustafakucuk0** [JCBrouwer/maua-stylegan2#24]
Hello! First of all, thank you for this wonderful repo. I am wondering that do you have any plan to make this project StyleGAN 3 compatible with. If so, I would like to use this project in my art project. I am extremely open to contributing if you have any plans.

Thanks!

**Comment by JCBrouwer** [comment]
Yes, I am definitely planning to. The audio-reactive latents can already be used directly in StyleGAN3 (just requires a new render script that feeds StyleGAN3 in the correct way), however network bending and rewriting will require some changes.

I'm actually working on a way to make the entire process support any GAN using a wrapper interface. Hopefully this way it'll be easier to extend to new networks in the future.

**Comment by mustafakucuk0** [comment]
Do you have any deadline for this change?

**Comment by JCBrouwer** [comment]
I actually need an audio-reactive trailer by Monday, so I could add a simple render script prototype by then, but the clean multi-GAN support framework and network bending stuff is probably on a longer timeline.

**Comment by mustafakucuk0** [comment]
I see. Thank you for your time and good luck in advance with your work!
