### ISSUE TITLE
Stylegan2-ADA PyTorch

### ISSUE THREAD

**Issue by mustafakucuk0** [JCBrouwer/maua-stylegan2#25]
Hi. I am trying to use your code with my locally trained model. I trained my model with stylegan2-ADA PyTorch but I cannot use your code directly because I get errors. Do I need to train with the original StyleGAN2, not ADA? Isn't this report compatible with ADA implementation?

Thanks.

**Comment by JCBrouwer** [comment]
The `convert_weight.py` in this repo can't handle the newer ADA pytorch version.

You should be able to convert with this notebook by @dvschultz though https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/SG2_ADA_PT_to_Rosinality.ipynb

I've been working on a big clean-up / overhaul of this repo for a while, cuz it's honestly in a pretty difficult to use state as you've noticed

**Comment by mustafakucuk0** [comment]
Thanks!
