### ISSUE TITLE
about method 'apply'

### ISSUE THREAD

**Issue by hui-vigil** [JCBrouwer/maua-stylegan2#26]
hi，UpFirDn2d.apply(
        inp, kernel, (up, up), (down, down), (pad[0], pad[1], pad[0], pad[1])
    )
but i didn't found the method 'apply' in class UpFirDn2d or Function, could you tell where the 'apply' defined, thank you

**Comment by JCBrouwer** [comment]
This is a method defined by the super class, [`torch.autograd.Function`](https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html).

Basically, you define the forward and backward pass for the operation and then using `.apply()` ensures that PyTorch's autograd keeps track of all the graph info / gradients correctly.
