### ISSUE TITLE
KeyError: 'G_mapping/Dense2/weight'

### ISSUE THREAD

**Issue by IvonaTau** [JCBrouwer/maua-stylegan2#4]
Hi, 

I get this error when trying to convert a model trained with stylegan2-ada repo (running in the collab notebook).

`!python ../stylegan2-pytorch/convert_weight.py --gen network-snapshot-000887.pkl --repo ../stylegan2-ada/`

output:

```Setting up TensorFlow plugin "fused_bias_act.cu": Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Loading... Done.
Traceback (most recent call last):
  File "../stylegan2-pytorch/convert_weight.py", line 242, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size)
  File "../stylegan2-pytorch/convert_weight.py", line 144, in fill_statedict
    update(state_dict, convert_dense(vars, f"G_mapping/Dense{i}", f"style.{i + 1}"))
  File "../stylegan2-pytorch/convert_weight.py", line 82, in convert_dense
    weight = vars[source_name + "/weight"].value().eval()
KeyError: 'G_mapping/Dense2/weight'
```

Do you know what might be wrong?

**Comment by JCBrouwer** [comment]
Hello, it looks like the checkpoint that you're converting is missing some layers that convert_weight.py is expecting.

Did you train the network with the 'auto' config? By default that uses only 2 mapping layers while the older configs all have 8.

I think you should be able to fix it by changing some 8s to 2s in the following lines:

https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py#L143

https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py#L240

https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py#L251

PS in terms of quality often those extra mapping layers can help quite a bit if your dataset is large/varied enough

**Comment by IvonaTau** [comment]
Thanks, that works for the conversion part.
But then  `generate_audiovisual.generate` returns:

```RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "style.3.weight", "style.3.bias", "style.4.weight", "style.4.bias", "style.5.weight", "style.5.bias", "style.6.weight", "style.6.bias", "style.7.weight", "style.7.bias", "style.8.weight", "style.8.bias". ```

Where should I remove these layers from Generator definition?

**Comment by JCBrouwer** [comment]
Ah yeah, you need to specify `n_mlp=2` to generate()

**Comment by IvonaTau** [comment]
Thanks it solves it!
